apiVersion: v1
kind: Service
metadata:
  name: gestao-pedidos
spec:
  type: NodePort #trocar para load balance
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32700
  selector:
    app: gestao-pedidos
    


    